# Generated by Django 6.1 on 2026-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
