# Generated by Django 6.1 on 2026-08-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='rende_quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receita',
            name='rende_unidade',
            field=models.CharField(default='Litro de água', max_length=30),
        ),
    ]
